export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_LOCATIONS_COMPLETE = 'FETCH_LOCATIONS_COMPLETE';
export const FETCH_LOCATIONS_ERROR = 'FETCH_LOCATIONS_ERROR';
export const SEARCH_LOCATION = 'SEARCH_LOCATION';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
