export const FETCH_LOCATIONS_REQUEST = 'FETCH_LOCATIONS_REQUEST';
export const FETCH_LOCATIONS_REQUEST_COMPLETE =
  'FETCH_LOCATIONS_REQUEST_COMPLETE';
export const FETCH_LOCATIONS_REQUEST_ERROR = 'FETCH_LOCATIONS_REQUEST_ERROR';
export const SEARCH_LOCATION = 'SEARCH_LOCATION';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
